name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Prepare to deploy
      run: |
        mkdir -p deploy/dist
        cp example/* deploy/
        cp dist/* deploy/dist/
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: deploy # The folder the action should deploy.
        CLEAN: true
